import "./globals.css"
import { Providers } from "@/components/providers"
import { RootScrollArea } from "@/components/root-scroll-area"
import { cn } from "@/lib/utils"
import { GeistMono } from "geist/font/mono"
import { GeistSans } from "geist/font/sans"
import type { Metadata, Viewport } from "next"
import type { ReactNode } from "react"

const TITLE = "Create Next App"
const DESCRIPTION = "Generated by create next app"

export const metadata: Metadata = {
	title: TITLE,
	description: DESCRIPTION,
	openGraph: {
		title: TITLE,
		description: DESCRIPTION,
		type: "website"
	}
}

export const viewport: Viewport = {
	width: "device-width",
	initialScale: 1,
	maximumScale: 1,
	userScalable: false,
	interactiveWidget: "resizes-visual",
	themeColor: [
		{ media: "(prefers-color-scheme: light)", color: "0 0% 100%" },
		{ media: "(prefers-color-scheme: dark)", color: "222.2 84% 4.9%" }
	]
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html
			lang="en"
			suppressHydrationWarning
			className={cn(
				"scroll-pt-[calc(var(--my-prefix-safeAreaInsetTop)+var(--my-prefix-contentSafeAreaInsetTop))]",
				"scroll-pb-[calc(var(--my-prefix-safeAreaInsetBottom)+var(--my-prefix-contentSafeAreaInsetBottom))]",
				"scroll-pl-[calc(var(--my-prefix-safeAreaInsetLeft)+var(--my-prefix-contentSafeAreaInsetLeft))]",
				"scroll-pr-[calc(var(--my-prefix-safeAreaInsetRight)+var(--my-prefix-contentSafeAreaInsetRight))]"
			)}
		>
			<body
				className={cn(
					"font-sans",
					"antialiased",
					GeistSans.variable,
					GeistMono.variable,
					"pt-[calc(var(--my-prefix-safeAreaInsetTop,0px)+var(--my-prefix-contentSafeAreaInsetTop))]",
					"pb-[calc(var(--my-prefix-safeAreaInsetBottom,0px)+var(--my-prefix-contentSafeAreaInsetBottom))]",
					"pl-[calc(var(--my-prefix-safeAreaInsetLeft,0px)+var(--my-prefix-contentSafeAreaInsetLeft))]",
					"pr-[calc(var(--my-prefix-safeAreaInsetRight,0px)+var(--my-prefix-contentSafeAreaInsetRight))]",
					"h-[100vh]",
					"w-full"
				)}
			>
				<RootScrollArea
					className={cn(
						"h-[calc(100vh-var(--my-prefix-safeAreaInsetTop)-var(--my-prefix-contentSafeAreaInsetTop)-var(--my-prefix-safeAreaInsetBottom)-var(--my-prefix-contentSafeAreaInsetBottom)-10px)]",
						"w-full"
					)}
				>
					<main className={cn("p-4")}>
						<Providers>{children}</Providers>
					</main>
					<div className={cn("h-[400px]")} />
				</RootScrollArea>
			</body>
		</html>
	)
}
