import "./globals.css"
import { Providers } from "@/components/providers"
import { ScrollArea } from "@/components/ui/scroll-area"
import { cn } from "@/lib/utils"
import { GeistMono } from "geist/font/mono"
import { GeistSans } from "geist/font/sans"
import type { Metadata, Viewport } from "next"
import type { ReactNode } from "react"

const TITLE = "Create Next App"
const DESCRIPTION = "Generated by create next app"

export const metadata: Metadata = {
	title: TITLE,
	description: DESCRIPTION,
	openGraph: {
		title: TITLE,
		description: DESCRIPTION,
		type: "website"
	}
}

export const viewport: Viewport = {
	width: "device-width",
	initialScale: 1,
	maximumScale: 1,
	userScalable: false,
	interactiveWidget: "resizes-visual",
	themeColor: [
		{ media: "(prefers-color-scheme: light)", color: "0 0% 100%" },
		{ media: "(prefers-color-scheme: dark)", color: "222.2 84% 4.9%" }
	]
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					"font-sans",
					"antialiased",
					GeistSans.variable,
					GeistMono.variable,
					"pt-[calc(var(--my-prefix-safeAreaInsetTop,0px)+var(--my-prefix-contentSafeAreaInsetTop))]",
					"pb-[calc(var(--my-prefix-safeAreaInsetBottom,0px)+var(--my-prefix-contentSafeAreaInsetBottom))]",
					"pl-[calc(var(--my-prefix-safeAreaInsetLeft,0px)+var(--my-prefix-contentSafeAreaInsetLeft))]",
					"pr-[calc(var(--my-prefix-safeAreaInsetRight,0px)+var(--my-prefix-contentSafeAreaInsetRight))]",
					"h-[var(--my-prefix-stableHeight)]",
					"w-full"
				)}
			>
				<main className={cn("border", "border-blue-500", "p-4")}>
					<ScrollArea
						className={cn(
							"h-[calc(var(--my-prefix-stableHeight)-var(--my-prefix-safeAreaInsetTop)-var(--my-prefix-contentSafeAreaInsetTop)-var(--my-prefix-safeAreaInsetBottom)-var(--my-prefix-contentSafeAreaInsetBottom))]",
							"w-[--my-prefix-width]",
							"border",
							"border-red-500"
						)}
					>
						<Providers>{children}</Providers>
						<div className={cn("h-[300px]")} />
					</ScrollArea>
				</main>
			</body>
		</html>
	)
}
